"use client";

import { useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { Download } from "lucide-react";
import type { Statement } from "@/lib/types";
import { formatCurrency } from "@/lib/format";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { Reveal } from "@/components/ui/Reveal";

/**
 * Colour values below mirror the design tokens in globals.css (navy-900,
 * gold-500, sand-300, ink-500) — the printable page is a standalone document
 * outside Tailwind, so tokens are inlined.
 */
const PRINT_NAVY = "#0b1f33";
const PRINT_GOLD = "#c9a45c";
const PRINT_BORDER = "#d9cdb8";
const PRINT_MUTED = "#6b6459";

// TODO: replace with a real PDF service (server-rendered statement PDFs)
// before production — this demo opens a printable window instead.
function statementHtml(statement: Statement, clientName: string): string {
  const rows: [string, string][] = [
    ["Gross rental income", formatCurrency(statement.gross)],
    ["BellaVere management fee (18%)", `− ${formatCurrency(statement.fee)}`],
    ["Expenses", `− ${formatCurrency(statement.expenses)}`],
  ];
  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>BellaVere owner statement — ${statement.period}</title>
</head>
<body style="margin:0;padding:48px;font-family:Georgia,'Times New Roman',serif;color:${PRINT_NAVY};background:#ffffff;">
  <div style="max-width:640px;margin:0 auto;">
    <div style="display:flex;justify-content:space-between;align-items:baseline;border-bottom:2px solid ${PRINT_GOLD};padding-bottom:16px;">
      <span style="font-size:26px;letter-spacing:0.08em;">Bella<span style="color:${PRINT_GOLD};">Vere</span></span>
      <span style="font-size:12px;color:${PRINT_MUTED};letter-spacing:0.12em;text-transform:uppercase;">Owner statement</span>
    </div>
    <h1 style="font-size:28px;font-weight:normal;margin:28px 0 4px;">${statement.period}</h1>
    <p style="margin:0 0 28px;font-size:14px;color:${PRINT_MUTED};font-family:Helvetica,Arial,sans-serif;">Prepared for ${clientName}</p>
    <table style="width:100%;border-collapse:collapse;font-family:Helvetica,Arial,sans-serif;font-size:14px;">
      ${rows
        .map(
          ([label, value]) => `<tr>
        <td style="padding:12px 0;border-bottom:1px solid ${PRINT_BORDER};">${label}</td>
        <td style="padding:12px 0;border-bottom:1px solid ${PRINT_BORDER};text-align:right;">${value}</td>
      </tr>`
        )
        .join("")}
      <tr>
        <td style="padding:16px 0;font-weight:bold;font-size:16px;">Net payout</td>
        <td style="padding:16px 0;font-weight:bold;font-size:16px;text-align:right;color:${PRINT_NAVY};">${formatCurrency(statement.net)}</td>
      </tr>
    </table>
    <p style="margin:24px 0 0;font-size:12px;color:${PRINT_MUTED};font-family:Helvetica,Arial,sans-serif;">Expenses = maintenance work and recurring upkeep (pool, garden, housekeeping)</p>
    <p style="margin:40px 0 0;padding-top:16px;border-top:1px solid ${PRINT_BORDER};font-size:11px;color:${PRINT_MUTED};font-family:Helvetica,Arial,sans-serif;">This is a demonstration statement generated by the BellaVere demo portal. Figures are illustrative only and do not represent a real payout.</p>
  </div>
</body>
</html>`;
}

export function StatementsTable({
  statements,
  clientName,
}: {
  statements: Statement[];
  clientName: string;
}) {
  const [popupBlocked, setPopupBlocked] = useState(false);

  const download = (statement: Statement) => {
    const win = window.open("", "_blank");
    if (!win) {
      // Pop-up blocked — surface an inline note instead of failing silently.
      setPopupBlocked(true);
      return;
    }
    setPopupBlocked(false);
    win.document.write(statementHtml(statement, clientName));
    win.document.close();
    win.focus();
    win.print();
  };

  return (
    <Reveal>
      <div aria-live="polite">
        <AnimatePresence>
          {popupBlocked ? (
            <motion.p
              initial={{ opacity: 0, y: -6 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.25 }}
              className="mb-4 rounded-xl border border-warning/30 bg-warning/10 px-4 py-3 text-sm text-warning"
            >
              Your browser blocked the statement window. Allow pop-ups for this
              site and try again.
            </motion.p>
          ) : null}
        </AnimatePresence>
      </div>

      {/* Desktop table */}
      <Card className="hidden overflow-x-auto md:block">
        <table className="w-full min-w-[720px] text-left text-sm">
          <thead>
            <tr className="border-b border-sand-300 text-xs uppercase tracking-wide text-ink-500">
              <th scope="col" className="px-5 py-3.5 font-medium">
                Period
              </th>
              <th scope="col" className="px-5 py-3.5 text-right font-medium">
                Gross rental
              </th>
              <th scope="col" className="px-5 py-3.5 text-right font-medium">
                BellaVere fee (18%)
              </th>
              <th scope="col" className="px-5 py-3.5 text-right font-medium">
                Expenses
              </th>
              <th scope="col" className="px-5 py-3.5 text-right font-medium">
                Net payout
              </th>
              <th scope="col" className="px-5 py-3.5 font-medium">
                Status
              </th>
              <th scope="col" className="px-5 py-3.5">
                <span className="sr-only">Download</span>
              </th>
            </tr>
          </thead>
          <tbody>
            {statements.map((s) => (
              <tr
                key={s.id}
                className="border-b border-sand-300/60 transition-colors duration-150 last:border-b-0 hover:bg-sand-50"
              >
                <td className="px-5 py-4 font-medium text-navy-900">
                  {s.period}
                </td>
                <td className="px-5 py-4 text-right text-ink-900">
                  {formatCurrency(s.gross)}
                </td>
                <td className="px-5 py-4 text-right text-ink-500">
                  −{formatCurrency(s.fee)}
                </td>
                <td className="px-5 py-4 text-right text-ink-500">
                  −{formatCurrency(s.expenses)}
                </td>
                <td className="px-5 py-4 text-right font-semibold text-navy-900">
                  {formatCurrency(s.net)}
                </td>
                <td className="px-5 py-4">
                  <Badge tone="success">Paid</Badge>
                </td>
                <td className="px-5 py-4 text-right">
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => download(s)}
                  >
                    <Download className="size-4" aria-hidden />
                    Download PDF
                  </Button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </Card>

      {/* Mobile: stacked cards with the same data */}
      <ul className="space-y-3 md:hidden">
        {statements.map((s) => (
          <li key={s.id}>
            <Card className="p-5">
              <div className="flex items-start justify-between gap-3">
                <p className="font-medium text-navy-900">{s.period}</p>
                <Badge tone="success">Paid</Badge>
              </div>
              <dl className="mt-3 space-y-1.5 text-sm">
                <div className="flex justify-between">
                  <dt className="text-ink-500">Gross rental</dt>
                  <dd className="text-ink-900">{formatCurrency(s.gross)}</dd>
                </div>
                <div className="flex justify-between">
                  <dt className="text-ink-500">BellaVere fee (18%)</dt>
                  <dd className="text-ink-500">−{formatCurrency(s.fee)}</dd>
                </div>
                <div className="flex justify-between">
                  <dt className="text-ink-500">Expenses</dt>
                  <dd className="text-ink-500">−{formatCurrency(s.expenses)}</dd>
                </div>
                <div className="flex justify-between border-t border-sand-300 pt-2">
                  <dt className="font-medium text-navy-900">Net payout</dt>
                  <dd className="font-semibold text-navy-900">
                    {formatCurrency(s.net)}
                  </dd>
                </div>
              </dl>
              <Button
                variant="outline"
                size="sm"
                onClick={() => download(s)}
                className="mt-4 w-full"
              >
                <Download className="size-4" aria-hidden />
                Download PDF
              </Button>
            </Card>
          </li>
        ))}
      </ul>
    </Reveal>
  );
}
